#!/usr/bin/env bash
# mnemo installer (Linux / macOS).
#
# Idempotent: rerunning on an already-installed setup is a no-op.
#
# Steps:
#   1. Verify Python 3.11+ and `uv` are available.
#   2. Sync the daemon's dependencies via `uv sync`.
#   3. Symlink the venv's `mnemo` binary into ~/.local/bin so it's on PATH.
#   4. Register the `mnemo mcp` server with Claude Code + print the two
#      `/plugin` commands that install the plugin (commands/hooks/skills).
#      (Modern Claude Code is marketplace-driven: a directory under
#      ~/.claude/plugins is IGNORED unless registered, so we no longer
#      symlink there -- that silently did nothing.)
#   5. Run `mnemo init` to register Scope B sources.
#
# Flags:
#   --no-init          Skip step 5.
#   --no-mcp           Skip the `claude mcp add` registration in step 4.
#   --bin-dir=<path>   Override the install dir for the `mnemo` shim.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")" && pwd)"
DAEMON_DIR="$REPO_ROOT/daemon"
DEFAULT_BIN_DIR="$HOME/.local/bin"

DO_INIT=1
DO_MCP=1
BIN_DIR="$DEFAULT_BIN_DIR"

for arg in "$@"; do
    case "$arg" in
        --no-init) DO_INIT=0 ;;
        --no-mcp) DO_MCP=0 ;;
        --bin-dir=*) BIN_DIR="${arg#--bin-dir=}" ;;
        --help|-h)
            grep '^#' "$0" | sed 's/^# \?//'
            exit 0
            ;;
        *)
            echo "unknown flag: $arg (try --help)" >&2
            exit 2
            ;;
    esac
done

log()   { printf '\033[36m[mnemo]\033[0m %s\n' "$*"; }
ok()    { printf '\033[32m[ok]\033[0m    %s\n' "$*"; }
warn()  { printf '\033[33m[warn]\033[0m  %s\n' "$*" >&2; }
fail()  { printf '\033[31m[fail]\033[0m  %s\n' "$*" >&2; exit 1; }

# --- 1. Prerequisites -----------------------------------------------------

if ! command -v python3 >/dev/null 2>&1; then
    fail "python3 not found. Install Python 3.11+ first."
fi

PY_VERSION=$(python3 -c 'import sys; print("%d.%d" % sys.version_info[:2])')
PY_MAJOR=${PY_VERSION%.*}
PY_MINOR=${PY_VERSION#*.}
if [ "$PY_MAJOR" -lt 3 ] || { [ "$PY_MAJOR" -eq 3 ] && [ "$PY_MINOR" -lt 11 ]; }; then
    fail "Python 3.11+ required (found $PY_VERSION)."
fi
ok "Python $PY_VERSION"

if ! command -v uv >/dev/null 2>&1; then
    warn "uv not found. Install with:"
    warn "  curl -LsSf https://astral.sh/uv/install.sh | sh"
    fail "Install uv, then re-run this script."
fi
ok "uv $(uv --version | awk '{print $2}')"

# --- 2. Sync daemon deps --------------------------------------------------

log "syncing daemon dependencies (this may take a minute on first run)"
( cd "$DAEMON_DIR" && uv sync )
ok "daemon deps installed"

# --- 3. Shim the mnemo binary onto PATH -----------------------------------
#
# uv creates a different venv layout per OS:
#   Unix:    .venv/bin/{python,mnemo}
#   Windows: .venv/Scripts/{python.exe,mnemo.exe}
#
# We avoid hard-linking the binary directly. Instead we write a small bash
# wrapper that calls the venv's Python with `-m mnemo.cli`. This works
# uniformly under bash (Linux, macOS, Git Bash on Windows).

if [ -x "$DAEMON_DIR/.venv/bin/python" ]; then
    VENV_PYTHON="$DAEMON_DIR/.venv/bin/python"
elif [ -f "$DAEMON_DIR/.venv/Scripts/python.exe" ]; then
    VENV_PYTHON="$DAEMON_DIR/.venv/Scripts/python.exe"
else
    fail "expected venv python under $DAEMON_DIR/.venv/{bin,Scripts}/ but it's missing"
fi

mkdir -p "$BIN_DIR"
SHIM="$BIN_DIR/mnemo"

cat > "$SHIM" <<EOF
#!/usr/bin/env bash
# mnemo CLI shim - generated by install.sh, do not edit by hand.
exec "$VENV_PYTHON" -m mnemo.cli "\$@"
EOF
chmod +x "$SHIM"
ok "mnemo shim -> $SHIM (calls $VENV_PYTHON)"

if ! echo ":$PATH:" | grep -q ":$BIN_DIR:"; then
    warn "$BIN_DIR is not on PATH."
    warn "Add this to your shell profile (.bashrc / .zshrc / etc.):"
    warn "  export PATH=\"$BIN_DIR:\$PATH\""
fi

# --- 4. Register the MCP server + print the /plugin commands --------------
#
# Claude Code is marketplace-driven: the plugin (commands/hooks/skills) is
# enabled by two /plugin commands the USER runs INSIDE Claude Code -- not by
# copying files. We register the MCP tool server here so the mnemo_* tools
# resolve, then print those two commands at the end.

if [ "$DO_MCP" -eq 1 ]; then
    if command -v claude >/dev/null 2>&1; then
        if claude mcp list 2>/dev/null | grep -qw mnemo; then
            ok "MCP server 'mnemo' already registered"
        elif claude mcp add mnemo -- mnemo mcp >/dev/null 2>&1; then
            ok "registered MCP server (claude mcp add mnemo -- mnemo mcp)"
        else
            warn "could not auto-register the MCP server; run it manually:"
            warn "  claude mcp add mnemo -- mnemo mcp"
        fi
    else
        warn "'claude' not on PATH; register the MCP server manually:"
        warn "  claude mcp add mnemo -- mnemo mcp"
        warn "  (other hosts: see docs/integrations/)"
    fi
fi

# --- 5. Register default sources ------------------------------------------

if [ "$DO_INIT" -eq 1 ]; then
    log "registering default Scope B sources"
    "$SHIM" init || warn "mnemo init failed (you can run it manually later)"
fi

# --- Done -----------------------------------------------------------------

cat <<EOF

Done. To finish wiring mnemo into Claude Code:

  1. In Claude Code, run these two commands, then RESTART Claude Code
     (the /mnemo-* commands appear immediately; the hooks load at session start):
       /plugin marketplace add mmct-jsc/mnemo
       /plugin install mnemo@mnemo
  2. Run 'mnemo reindex' to ingest your memory (first run downloads MiniLM ~22MB).
  3. Run 'mnemo doctor' to verify every link is green.

  - If you saw the PATH warning above, add $BIN_DIR to PATH and re-open your shell.
  - 'mnemo daemon start' enables the web UI at http://127.0.0.1:7373/ (optional).
EOF
