"""Tests for the v2.6 safeguards module.

v2.6 phase 2: pure-function heuristics for the reindex pipeline.
``classify_file`` returns 'ok' / 'auto_skipped' / 'suspicious'; the
'malformed' classification is added by ingest in phase 3 when an
actual parse raises.
"""

from __future__ import annotations

import os
import secrets
from pathlib import Path

from mnemo import safeguards

# --- classify_file orchestration --------------------------------------------


def test_classify_ok_for_normal_markdown(tmp_path: Path) -> None:
    p = tmp_path / "doc.md"
    p.write_text("# Hello\n\nNormal docs with plain text.\n")
    c = safeguards.classify_file(p)
    assert c.category == "ok"
    assert c.reason is None


def test_classify_ok_for_normal_python(tmp_path: Path) -> None:
    p = tmp_path / "foo.py"
    p.write_text("def hello():\n    return 'world'\n")
    c = safeguards.classify_file(p)
    assert c.category == "ok"


def test_classify_unsupported_extension(tmp_path: Path) -> None:
    p = tmp_path / "image.xyz"
    p.write_text("not text")
    c = safeguards.classify_file(p)
    assert c.category == "auto_skipped"
    assert c.reason is not None
    assert c.reason.startswith("unsupported_ext")


def test_classify_oversize(tmp_path: Path) -> None:
    p = tmp_path / "big.md"
    p.write_bytes(b"x" * (6 * 1024 * 1024))  # 6 MiB > 5 MiB default
    c = safeguards.classify_file(p)
    assert c.category == "auto_skipped"
    assert c.reason is not None
    assert c.reason.startswith("oversize")


def test_classify_respects_custom_size_limit(tmp_path: Path) -> None:
    p = tmp_path / "small.md"
    p.write_bytes(b"x" * 200)
    c = safeguards.classify_file(p, size_limit_bytes=100)
    assert c.category == "auto_skipped"
    assert c.reason is not None
    assert "oversize" in c.reason


def test_classify_accepts_content_bytes_param(tmp_path: Path) -> None:
    """Pre-read content bypasses the read inside classify_file."""
    p = tmp_path / "doc.md"
    p.write_text("# Real content")
    c = safeguards.classify_file(p, content_bytes=b"# Different content")
    assert c.category == "ok"


# --- is_binary_masquerading_as_text -----------------------------------------


def test_binary_masquerade_detects_nul_heavy_content() -> None:
    # Build a sample with ~40% NUL bytes.
    content = b"".join(b"a\x00\x00" if i % 2 else b"b" for i in range(1000))
    assert safeguards.is_binary_masquerading_as_text(content) is not None


def test_binary_masquerade_passes_normal_text() -> None:
    assert safeguards.is_binary_masquerading_as_text(b"hello world\nthis is normal text\n") is None


def test_binary_masquerade_handles_empty_input() -> None:
    assert safeguards.is_binary_masquerading_as_text(b"") is None


def test_binary_masquerade_threshold_is_configurable() -> None:
    # 20% NUL ratio passes default 30% threshold, fails 10%.
    content = b"abcdefgh\x00\x00" * 100  # 20% nul
    assert safeguards.is_binary_masquerading_as_text(content, threshold=0.30) is None
    assert safeguards.is_binary_masquerading_as_text(content, threshold=0.10) is not None


# --- looks_like_secret ------------------------------------------------------


def test_looks_like_secret_pem_private_key(tmp_path: Path) -> None:
    p = tmp_path / "key.txt"
    content = (
        b"-----BEGIN RSA PRIVATE KEY-----\nMIIEpAIBAAKCAQEA...\n-----END RSA PRIVATE KEY-----\n"
    )
    reason = safeguards.looks_like_secret(p, content)
    assert reason is not None
    assert "private_key" in reason


def test_looks_like_secret_aws_access_key(tmp_path: Path) -> None:
    p = tmp_path / "creds.txt"
    content = b"AWS_ACCESS_KEY = AKIAIOSFODNN7EXAMPLE\n"
    reason = safeguards.looks_like_secret(p, content)
    assert reason is not None


def test_looks_like_secret_github_token(tmp_path: Path) -> None:
    p = tmp_path / "out.txt"
    content = b"GH_TOKEN=ghp_abcdefghijklmnopqrstuvwxyz0123456789\n"
    reason = safeguards.looks_like_secret(p, content)
    assert reason is not None
    assert "github_token" in reason


def test_looks_like_secret_dotenv_shape(tmp_path: Path) -> None:
    p = tmp_path / ".env"
    content = b"DATABASE_URL=postgres://user:pass@host/db\nAPI_KEY=secret123\nDEBUG=true\n"
    reason = safeguards.looks_like_secret(p, content)
    assert reason is not None
    assert "dotenv" in reason


def test_looks_like_secret_passes_normal_text(tmp_path: Path) -> None:
    p = tmp_path / "doc.md"
    content = b"# Normal docs\nNothing sketchy here. Just words.\n"
    assert safeguards.looks_like_secret(p, content) is None


# --- has_autogenerated_header -----------------------------------------------


def test_autogen_detects_at_generated() -> None:
    assert safeguards.has_autogenerated_header(b"// @generated by tool\nconst x = 1;\n") is not None


def test_autogen_detects_do_not_edit() -> None:
    assert (
        safeguards.has_autogenerated_header(
            b"// Code generated by tool. DO NOT EDIT.\npackage main\n"
        )
        is not None
    )


def test_autogen_detects_autogenerated() -> None:
    assert safeguards.has_autogenerated_header(b"# AUTOGENERATED -- do not modify\n") is not None


def test_autogen_passes_normal_file() -> None:
    assert safeguards.has_autogenerated_header(b"# Hello\n\nNormal handwritten content.\n") is None


def test_autogen_does_not_flag_docs_about_generators() -> None:
    """v2.6.0 polish: a BASE memory reference doc that DISCUSSES the
    autogen markers should not trip the heuristic. Real autogen files
    put the marker in the first 1-3 lines; documentation hits the
    word much later in the body. The 512 B window draws the line."""
    body = (
        b"---\n"
        b"name: reference-mnemo-index-scoring\n"
        b"type: memory_reference\n"
        b"base: true\n"
        b"---\n\n"
        b"# Reference: indexing + scoring\n\n"
        b"## 1. Safeguards heuristics\n\n"
        b"This section explains every heuristic in safeguards.py "
        b"so you can debug a surprising classification.\n\n"
        b"Padding to push the autogen-marker discussion past the\n"
        b"first 512 bytes. " + b"More padding. " * 20 + b"\n\n"
        b"### Heuristic 3: has_autogenerated_header\n\n"
        b"The function scans the file head for markers like @generated,\n"
        b"GENERATED FILE, AUTOGENERATED, AUTO-GENERATED, and the standard\n"
        b"Go DO NOT EDIT preamble. Real tools put these in the first\n"
        b"1-3 lines of the file.\n"
    )
    # The marker discussion lives past byte 512 -- false-positive avoided.
    assert safeguards.has_autogenerated_header(body) is None


# --- is_lock_minified_or_snapshot -------------------------------------------


def test_lock_detects_package_lock_json(tmp_path: Path) -> None:
    p = tmp_path / "package-lock.json"
    assert safeguards.is_lock_minified_or_snapshot(p) is not None


def test_lock_detects_uv_lock(tmp_path: Path) -> None:
    p = tmp_path / "uv.lock"
    assert safeguards.is_lock_minified_or_snapshot(p) is not None


def test_lock_detects_minified_js(tmp_path: Path) -> None:
    p = tmp_path / "app.min.js"
    assert safeguards.is_lock_minified_or_snapshot(p) is not None


def test_lock_detects_minified_css(tmp_path: Path) -> None:
    p = tmp_path / "style.min.css"
    assert safeguards.is_lock_minified_or_snapshot(p) is not None


def test_lock_detects_snapshot(tmp_path: Path) -> None:
    p = tmp_path / "component.test.tsx.snap"
    assert safeguards.is_lock_minified_or_snapshot(p) is not None


def test_lock_detects_sourcemap(tmp_path: Path) -> None:
    p = tmp_path / "app.js.map"
    assert safeguards.is_lock_minified_or_snapshot(p) is not None


def test_lock_passes_normal_filename(tmp_path: Path) -> None:
    p = tmp_path / "app.js"
    assert safeguards.is_lock_minified_or_snapshot(p) is None


# --- is_high_entropy_blob ---------------------------------------------------


def test_high_entropy_detects_random_data() -> None:
    random_data = secrets.token_bytes(8192)
    reason = safeguards.is_high_entropy_blob(random_data, threshold=7.5)
    assert reason is not None


def test_high_entropy_passes_normal_text() -> None:
    text = b"Hello world. This is normal English text with low entropy.\n" * 200
    assert safeguards.is_high_entropy_blob(text, threshold=7.5) is None


def test_high_entropy_skips_tiny_samples() -> None:
    assert safeguards.is_high_entropy_blob(b"short", threshold=7.5) is None


def test_high_entropy_threshold_configurable() -> None:
    """Entropy of plain English is around 4-5; a low threshold must still flag it."""
    text = b"Hello world. This is normal English text with low entropy.\n" * 200
    # Even normal text has SOME entropy; a very-low threshold should catch it.
    reason = safeguards.is_high_entropy_blob(text, threshold=3.0)
    assert reason is not None


# --- has_repeated_line_bloat ------------------------------------------------


def test_repeated_line_bloat_detects_log_dumps() -> None:
    line = b"the same log line over and over\n"
    content = line * 5000  # 160 KB+ and 100% repeated
    reason = safeguards.has_repeated_line_bloat(content, len(content))
    assert reason is not None


def test_repeated_line_bloat_skips_small_files() -> None:
    line = b"the same line\n"
    content = line * 50  # < 100 KB
    assert safeguards.has_repeated_line_bloat(content, len(content)) is None


def test_repeated_line_bloat_passes_diverse_log() -> None:
    content = b"\n".join(
        f"unique log line {i} {os.urandom(8).hex()}".encode() for i in range(10000)
    )
    assert safeguards.has_repeated_line_bloat(content, len(content)) is None


# --- is_build_output_name ---------------------------------------------------


def test_build_output_detects_bundle_js(tmp_path: Path) -> None:
    p = tmp_path / "bundle.js"
    assert safeguards.is_build_output_name(p) is not None


def test_build_output_detects_vendor_js(tmp_path: Path) -> None:
    p = tmp_path / "vendor.js"
    assert safeguards.is_build_output_name(p) is not None


def test_build_output_detects_dist_dir() -> None:
    p = Path("repo/dist/app.js")
    assert safeguards.is_build_output_name(p) is not None


def test_build_output_detects_node_modules() -> None:
    p = Path("repo/node_modules/foo/bar.js")
    assert safeguards.is_build_output_name(p) is not None


def test_build_output_detects_pycache() -> None:
    p = Path("pkg/__pycache__/m.cpython-313.pyc")
    assert safeguards.is_build_output_name(p) is not None


def test_build_output_passes_src_dir() -> None:
    p = Path("repo/src/app.js")
    assert safeguards.is_build_output_name(p) is None


# --- classify_file orchestration: heuristic ordering ------------------------


def test_classify_flags_bundle_js_as_suspicious(tmp_path: Path) -> None:
    """Filename-based heuristic fires before content checks."""
    p = tmp_path / "bundle.js"
    p.write_text("console.log('hello');\n")
    c = safeguards.classify_file(p)
    assert c.category == "suspicious"
    assert c.reason is not None


def test_classify_flags_pem_key_file_as_suspicious(tmp_path: Path) -> None:
    p = tmp_path / "key.txt"
    p.write_bytes(
        b"-----BEGIN RSA PRIVATE KEY-----\nMIIEpAIBAAKCAQEA...\n-----END RSA PRIVATE KEY-----\n"
    )
    c = safeguards.classify_file(p)
    assert c.category == "suspicious"
    assert c.reason is not None
    assert "private_key" in c.reason


def test_classify_flags_min_js_as_suspicious(tmp_path: Path) -> None:
    p = tmp_path / "app.min.js"
    p.write_text("var x=1;")
    c = safeguards.classify_file(p)
    assert c.category == "suspicious"


def test_classify_flags_high_entropy_blob(tmp_path: Path) -> None:
    p = tmp_path / "blob.md"
    p.write_bytes(secrets.token_bytes(16_384))
    c = safeguards.classify_file(p)
    assert c.category == "suspicious"


def test_classify_extension_check_before_size(tmp_path: Path) -> None:
    """Even a 10MB .xyz fails on extension, not size, since extension is cheaper."""
    p = tmp_path / "big.xyz"
    p.write_bytes(b"x" * (10 * 1024 * 1024))
    c = safeguards.classify_file(p)
    assert c.category == "auto_skipped"
    assert c.reason is not None
    assert c.reason.startswith("unsupported_ext")


def test_classify_handles_missing_file(tmp_path: Path) -> None:
    p = tmp_path / "ghost.md"
    c = safeguards.classify_file(p)
    assert c.category == "auto_skipped"
    assert c.reason is not None
